/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/mkiol/dev/Jupii/desktop/../dbus/org.freedesktop.Tracker1.Steroids.xml -p ../core/dbus_tracker_inf
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "../core/dbus_tracker_inf.h"

/*
 * Implementation of interface class OrgFreedesktopTracker1SteroidsInterface
 */

OrgFreedesktopTracker1SteroidsInterface::OrgFreedesktopTracker1SteroidsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopTracker1SteroidsInterface::~OrgFreedesktopTracker1SteroidsInterface()
{
}

