/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp /home/mersdk/share/dev/Jupii/sailfish/../dbus/org.jupii.xml -a ../core/dbus_jupii_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "../core/dbus_jupii_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PlayerAdaptor
 */

PlayerAdaptor::PlayerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PlayerAdaptor::~PlayerAdaptor()
{
    // destructor
}

bool PlayerAdaptor::canControl() const
{
    // get the value of property canControl
    return qvariant_cast< bool >(parent()->property("canControl"));
}

void PlayerAdaptor::add(const QString &url, const QString &name, const QString &author, const QString &description, int type, const QString &app, const QString &icon, bool once, bool play, bool focus)
{
    // handle method call org.jupii.Player.add
    QMetaObject::invokeMethod(parent(), "add", Q_ARG(QString, url), Q_ARG(QString, name), Q_ARG(QString, author), Q_ARG(QString, description), Q_ARG(int, type), Q_ARG(QString, app), Q_ARG(QString, icon), Q_ARG(bool, once), Q_ARG(bool, play), Q_ARG(bool, focus));
}

void PlayerAdaptor::addPath(const QString &path, const QString &name)
{
    // handle method call org.jupii.Player.addPath
    QMetaObject::invokeMethod(parent(), "addPath", Q_ARG(QString, path), Q_ARG(QString, name));
}

void PlayerAdaptor::addPathOnce(const QString &path, const QString &name)
{
    // handle method call org.jupii.Player.addPathOnce
    QMetaObject::invokeMethod(parent(), "addPathOnce", Q_ARG(QString, path), Q_ARG(QString, name));
}

void PlayerAdaptor::addPathOnceAndPlay(const QString &path, const QString &name)
{
    // handle method call org.jupii.Player.addPathOnceAndPlay
    QMetaObject::invokeMethod(parent(), "addPathOnceAndPlay", Q_ARG(QString, path), Q_ARG(QString, name));
}

void PlayerAdaptor::addUrl(const QString &url, const QString &name)
{
    // handle method call org.jupii.Player.addUrl
    QMetaObject::invokeMethod(parent(), "addUrl", Q_ARG(QString, url), Q_ARG(QString, name));
}

void PlayerAdaptor::addUrlOnce(const QString &url, const QString &name)
{
    // handle method call org.jupii.Player.addUrlOnce
    QMetaObject::invokeMethod(parent(), "addUrlOnce", Q_ARG(QString, url), Q_ARG(QString, name));
}

void PlayerAdaptor::addUrlOnceAndPlay(const QString &url, const QString &name)
{
    // handle method call org.jupii.Player.addUrlOnceAndPlay
    QMetaObject::invokeMethod(parent(), "addUrlOnceAndPlay", Q_ARG(QString, url), Q_ARG(QString, name));
}

void PlayerAdaptor::appendPath(const QString &path)
{
    // handle method call org.jupii.Player.appendPath
    QMetaObject::invokeMethod(parent(), "appendPath", Q_ARG(QString, path));
}

void PlayerAdaptor::clearPlaylist()
{
    // handle method call org.jupii.Player.clearPlaylist
    QMetaObject::invokeMethod(parent(), "clearPlaylist");
}

