/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbus/org.jupii.xml -a src/app_adaptor -p src/app_interface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "src/app_interface.h"

/*
 * Implementation of interface class OrgJupiiPlayerInterface
 */

OrgJupiiPlayerInterface::OrgJupiiPlayerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgJupiiPlayerInterface::~OrgJupiiPlayerInterface()
{
}

