# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-jupii

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libavcodec.*|libavformat.*|libavutil.*|libavresample.*|libswscale.*|libmp3lame.*|libtag.*$
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Jupii
Version:    2.3.0
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://mozilla.org/MPL/2.0/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-jupii.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(libcurl)
BuildRequires:  pkgconfig(audioresource)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pulseaudio-devel
BuildRequires:  desktop-file-utils

%description
Stream content from your mobile to UPnP/DLNA devices


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
